Repository lea927/drop-that-beat, pull requests merged in 2021-09, with the labels that each got.

#9 User model feature
  .github/workflows/rspec.yml
  .gitignore
  Gemfile.lock
  app/models/user.rb
  config/credentials.yml.enc
  config/credentials/test.yml.enc
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20210913123203_devise_create_users.rb
  db/migrate/20210913125431_add_index_to_user.rb
  db/schema.rb
  package.json
  spec/models/users_spec.rb
  test/factories/users.rb
  yarn.lock
Labels: State: In Progress, Type: Feature

#11 Room model feature
  app/models/room.rb
  app/models/room_track.rb
  db/migrate/20210913155353_create_rooms.rb
  db/migrate/20210913155524_add_room_ref_to_room_tracks.rb
  db/schema.rb
  spec/models/room_spec.rb
  test/factories/rooms.rb
Labels: Priority: High, State: In Progress, Type: Feature

#13 Create account feature
  app/assets/stylesheets/home_page.scss
  app/controllers/application_controller.rb
  app/controllers/home_page_controller.rb
  app/helpers/home_page_helper.rb
  app/javascript/packs/application.js
  app/javascript/stylesheets/application.scss
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/home_page/index.html.haml
  app/views/home_page/landing.html.haml
  app/views/layouts/_flash.html.haml
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.erb
  config/routes.rb
  public/boy-dj.svg
  public/girl-listening-music.svg
  public/girl-recording.svg
  public/logo.svg
  spec/system/create_user_spec.rb
Labels: Priority: High, Type: Feature, State: Complete

#28 Devise confirmable
  app/mailers/application_mailer.rb
  app/models/user.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/devise.rb
  db/migrate/20210914162347_add_confirmable_to_devise.rb
  db/schema.rb
  spec/system/create_user_spec.rb
Labels: Type: Feature, State: Complete

#32 [WIP] Room model add rounds attribute
  db/migrate/20210915115623_add_rounds_to_room.rb
  db/schema.rb
  spec/models/room_spec.rb
Labels: Priority: High, Type: Feature

#33 Update user model to add points attribute
  db/migrate/20210915131108_add_points_to_user.rb
  db/schema.rb
  spec/models/users_spec.rb
Labels: Priority: High, Type: Feature, State: Complete

#29 User login feature
  app/controllers/application_controller.rb
  app/views/devise/sessions/new.html.erb
  config/initializers/devise.rb
  spec/system/login_users_spec.rb
Labels: Priority: Medium, State: In Progress, Type: Feature

#34 Edit password
  app/views/devise/registrations/edit.html.erb
  app/views/layouts/_header.html.haml
  spec/system/create_user_spec.rb
  spec/system/edit_password_spec.rb
Labels: Type: ★ Enhancement, State: Complete

#36 Track model update
  Gemfile
  Gemfile.lock
  app/models/track.rb
  db/migrate/20210916121702_change_adam_id_column_to_string.rb
  db/schema.rb
  spec/models/track_spec.rb
  test/factories/tracks.rb
Labels: Priority: Medium

#42 Search rooms
  app/controllers/rooms_controller.rb
  app/models/room.rb
  app/views/layouts/_header.html.haml
  app/views/rooms/index.html.haml
  spec/system/search_game_rooms_spec.rb
  test/factories/rooms.rb
Labels: State: In Progress, Type: Feature

#41 [WIP] Search track
  Gemfile
  Gemfile.lock
  app/controllers/tracks_controller.rb
  app/helpers/application_helper.rb
  app/views/tracks/index.html.haml
  config/routes.rb
Labels: Type: ★ Enhancement, Priority: High, Type: Feature, State: Complete

#44 Callback for saving track attributes as lowercase
  app/models/track.rb
  spec/models/track_spec.rb
Labels: Type: ★ Enhancement

#47 Create game room feature
  app/controllers/home_page_controller.rb
  app/controllers/rooms_controller.rb
  app/models/room.rb
  app/views/home_page/index.html.haml
  app/views/rooms/edit.html.erb
  app/views/rooms/edit.html.haml
  spec/models/room_spec.rb
  spec/support/create_game_room.rb
  spec/support/sign_in_user.rb
  spec/system/create_game_rooms_spec.rb
  spec/system/list_game_rooms_spec.rb
  spec/system/search_game_rooms_spec.rb
  spec/system/setup_game_rooms_spec.rb
Labels: Priority: Medium, Type: Feature, State: Complete

#46 Fixes route to home page index
  app/controllers/home_page_controller.rb
  app/controllers/rooms_controller.rb
  config/routes.rb
Labels: Type: ★ Enhancement

#48 Search tracks using AJAX
  .github/workflows/rspec.yml
  app/controllers/tracks_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/views/rooms/edit.html.haml
  app/views/tracks/_search_tracks.html.haml
  app/views/tracks/_track.html.haml
  app/views/tracks/index.html.haml
  app/views/tracks/search.js.erb
  config/webpack/environment.js
  package.json
  spec/helpers/application_helper_spec.rb
  spec/support/cassettes/invalid/tracks/unknown.yml
  spec/support/cassettes/tracks/dua_lipa.yml
  spec/support/vcr.rb
  yarn.lock
Labels: Type: ★ Enhancement, Priority: Medium, State: Complete

#52 Retrieve and save track data
  app/controllers/tracks_controller.rb
  app/models/track.rb
  app/views/tracks/_track.html.haml
  config/routes.rb
  spec/models/track_spec.rb
Labels: Priority: Medium, Type: Feature, State: Ongoing Review

#58 Add tracks to room using AJAX
  app/controllers/tracks_controller.rb
  app/views/rooms/edit.html.haml
  app/views/tracks/_search_tracks.html.haml
  app/views/tracks/_track.html.haml
  app/views/tracks/create.js.erb
  app/views/tracks/search.js.erb
  config/routes.rb
  config/webpack/environment.js
  spec/rails_helper.rb
  spec/requests/tracks_controllers_spec.rb
  test/factories/rooms.rb
  test/factories/tracks.rb
  test/factories/users.rb
Labels: Priority: High, Type: Feature, State: Ongoing Review

#57 Delete game rooms
  app/controllers/rooms_controller.rb
  app/views/home_page/index.html.haml
  spec/system/delete_game_rooms_spec.rb
Labels: Type: Feature, State: Ongoing Review

#62 Remove tracks from rooms feature
  app/controllers/tracks_controller.rb
  app/views/rooms/edit.html.haml
  app/views/tracks/_track.html.haml
  config/routes.rb
  spec/requests/tracks_controllers_spec.rb
Labels: Priority: Medium, Type: Feature, State: Ongoing Review

#63 Validation for assigning duplicate tracks to room
  app/controllers/tracks_controller.rb
  app/models/room_track.rb
  db/migrate/20210922083440_add_index_to_room_tracks.rb
  db/schema.rb
  spec/models/room_spec.rb
  spec/requests/tracks_controllers_spec.rb
Labels: Priority: Medium, Type: Feature, State: Ongoing Review

#61 Max game rounds
  app/models/room.rb
  app/views/rooms/edit.html.haml
  spec/models/room_spec.rb
  spec/support/create_game_room.rb
  spec/system/setup_game_rooms_spec.rb
Labels: Type: ★ Enhancement, Priority: ① Low, State: Ongoing Review

#64 Search rooms by artist
  app/controllers/rooms_controller.rb
  app/models/room.rb
  spec/system/search_game_rooms_spec.rb
Labels: Type: ☹︎ Bug, Priority: Medium, State: Ongoing Review

#51 Show game room feature V1.0
  Gemfile.lock
  app/controllers/rooms_controller.rb
  app/views/rooms/_show.js.erb
  app/views/rooms/index.html.haml
  app/views/rooms/show.html.haml
  config/routes.rb
  db/seeds.rb
  spec/rails_helper.rb
  spec/requests/room_spec.rb
  spec/system/show_game_rooms_spec.rb
Labels: Type: ★ Enhancement, Priority: High, State: In Progress

#71 Playlist feature to play playlist upon clicking of start game button
  app/controllers/rooms_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/playlist.js
  app/views/rooms/show.html.haml
Labels: Priority: High, State: In Progress, Type: Feature

#65 Add github issue templates for standard documentation
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: Type: ✎ Docs, Priority: ① Low, State: Ongoing Review

#70 Bootstrap
  app/javascript/fonts/raleway/Raleway-Bold.ttf
  app/javascript/fonts/raleway/Raleway-ExtraBold.ttf
  app/javascript/fonts/raleway/Raleway-Medium.ttf
  app/javascript/packs/application.js
  app/javascript/stylesheets/_buttons.scss
  app/javascript/stylesheets/_typography.scss
  app/javascript/stylesheets/_variables.scss
  app/javascript/stylesheets/application.scss
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/home_page/landing.html.haml
  config/webpack/environment.js
  package.json
  yarn.lock
Labels: Type: ★ Enhancement, State: Ongoing Review

#78 Endpoint for posting answers and js async function for posting answers
  app/controllers/rooms_controller.rb
  app/views/rooms/show.html.haml
  config/routes.rb
  spec/requests/room_spec.rb
  spec/requests/rooms_spec.rb
Labels: Priority: High, Type: Feature, State: Complete

#79 Save track case based on the search result and perform case-insensitive search of rooms
  app/models/room.rb
  app/models/track.rb
Labels: Type: ★ Enhancement, Priority: ① Low, State: Complete

#81 Room and tracks json files to easily obtain data via AJAX
  app/controllers/tracks_controller.rb
  app/views/rooms/_room.json.jbuilder
  app/views/rooms/index.json.jbuilder
  app/views/rooms/show.json.jbuilder
  app/views/tracks/_track.json.jbuilder
  app/views/tracks/index.json.jbuilder
  app/views/tracks/show.json.jbuilder
  spec/requests/tracks_controllers_spec.rb
Labels: Priority: High, Type: Feature, State: Ongoing Review

#77 Progress bar
  app/javascript/packs/loader.js
  app/javascript/packs/playlist.js
  app/javascript/stylesheets/application.scss
  app/views/rooms/show.html.haml
  spec/rails_helper.rb
  spec/views/show.html.haml_spec.rb
Labels: Type: ★ Enhancement, Priority: Medium, State: Ongoing Review

#75 Game room choices
  app/controllers/rooms_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/choices.js
  app/javascript/stylesheets/_buttons.scss
  app/views/rooms/show.html.haml
  spec/system/start_game_spec.rb
Labels: Priority: High, Type: Feature, State: Ongoing Review

#85 Stop music when user exists the game room
  app/views/rooms/show.html.haml
Labels: Type: ☹︎ Bug, Priority: High, State: Ongoing Review

#92 Create track class in javascript
  app/javascript/packs/model/track.js
Labels: Priority: Medium, State: Complete, Type: Refactor

#93 Create question class
  app/javascript/packs/model/question.js
  app/javascript/packs/model/track.js
Labels: Priority: Medium, State: In Progress, Type: Refactor

#94 Create room class in javascript
  app/javascript/packs/model/question.js
  app/javascript/packs/model/room.js
Labels: Priority: Medium, State: In Progress, Type: Refactor

#83 Not allow users to play their own rooms
  Gemfile.lock
  app/controllers/rooms_controller.rb
  spec/system/show_game_rooms_spec.rb
Labels: Priority: Medium, Type: Feature, State: Complete

#100 Bump Heroku Fix (1)
  Procfile
Labels: Priority: High, State: In Progress

#101 Adds new credentials.yml
  config/credentials.yml.enc
Labels: Priority: High

#102 Bump Heroku Fix (3)
  app/helpers/application_helper.rb
Labels: Type: ☹︎ Bug, Priority: Medium

#103 Bump Heroku Fix (4)
  config/application.rb
Labels: Type: ☹︎ Bug, Priority: High

#104 Bump Heroku Fix (5)
  config/application.rb
Labels: Type: ☹︎ Bug, Priority: High

#106 Bump Heroku Fix (7)
  config/application.rb
Labels: Type: ☹︎ Bug, Priority: High

#107 Bump Heroku Fix (8)
  config/application.rb
Labels: Type: ☹︎ Bug, Priority: High

#108 Bump Heroku Fix (9)
  app/helpers/application_helper.rb
Labels: Priority: High

#95 Refactor game room
  app/controllers/rooms_controller.rb
  app/javascript/packs/api/index.js
  app/javascript/packs/application.js
  app/javascript/packs/choices.js
  app/javascript/packs/game.js
  app/javascript/packs/loader.js
  app/javascript/packs/model/question.js
  app/javascript/packs/model/room.js
  app/javascript/packs/model/track.js
  app/javascript/packs/playlist.js
  app/views/rooms/show.html.haml
  config/routes.rb
  spec/requests/rooms_spec.rb
Labels: Priority: High, State: Ongoing Review, Type: Refactor

#97 Header Style
  app/helpers/application_helper.rb
  app/javascript/stylesheets/_variables.scss
  app/javascript/stylesheets/application.scss
  app/views/layouts/_header.html.haml
  public/coin.svg
  public/navbar-brand-light.svg
  public/user.svg
Labels: Priority: Medium, Type: ❏ Visualization

#98 Login and Signup Style
  app/javascript/stylesheets/_buttons.scss
  app/javascript/stylesheets/_inputs.scss
  app/javascript/stylesheets/application.scss
  app/views/devise/registrations/new.html.erb
  app/views/devise/registrations/new.html.haml
  app/views/devise/sessions/new.html.erb
  app/views/devise/sessions/new.html.haml
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_header.html.haml
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.erb
  public/logo-dark.svg
  spec/system/create_user_spec.rb
  spec/system/edit_password_spec.rb
  spec/system/login_users_spec.rb
Labels: Priority: Medium, Type: ❏ Visualization
