Repository lea927/drop-that-beat, pull requests merged in 2021-10, with the labels that each got.

#110 Update posting of answers feature
  app/controllers/rooms_controller.rb
  app/javascript/packs/api/index.js
  app/javascript/packs/api/request.js
  app/javascript/packs/api/room.js
  app/javascript/packs/api/url.js
  app/views/rooms/show.html.haml
  spec/requests/rooms_spec.rb
Labels: Priority: High, Type: Feature, State: Ongoing Review

#119 Fix playlist playing multiple times
  app/javascript/packs/game.js
  app/views/rooms/show.html.haml
Labels: Type: ☹︎ Bug, Priority: High, State: Complete

#114 Home Style
  app/javascript/packs/application.js
  app/javascript/stylesheets/_inputs.scss
  app/javascript/stylesheets/application.scss
  app/views/home_page/index.html.haml
  package.json
  public/alert.svg
  public/music-note-list.svg
  spec/support/create_game_room.rb
  spec/system/create_game_rooms_spec.rb
  spec/system/delete_game_rooms_spec.rb
  spec/system/list_game_rooms_spec.rb
  yarn.lock
Labels: Priority: Medium, Type: ❏ Visualization, State: Ongoing Review

#116 Require minimum number of tracks
  app/controllers/rooms_controller.rb
  app/controllers/tracks_controller.rb
  app/models/room.rb
  app/views/home_page/index.html.haml
  app/views/rooms/_form.html.haml
  app/views/rooms/edit.html.haml
  app/views/rooms/new.html.erb
  app/views/rooms/new.html.haml
  app/views/tracks/_search_tracks.html.haml
  app/views/tracks/_track.html.haml
  spec/models/room_spec.rb
  spec/models/track_spec.rb
  spec/requests/rooms_spec.rb
  spec/requests/tracks_spec.rb
  spec/support/cassettes/tracks/coldplay.yml
  spec/support/cassettes/tracks/dua_lipa.yml
  spec/support/create_game_room.rb
  spec/support/vcr.rb
  spec/system/create_game_rooms_spec.rb
  spec/system/edit_game_rooms_spec.rb
  spec/system/list_game_rooms_spec.rb
  spec/system/search_game_rooms_spec.rb
  spec/system/setup_game_rooms_spec.rb
  spec/system/show_game_rooms_spec.rb
  spec/system/start_game_spec.rb
  spec/views/show.html.haml_spec.rb
  test/factories/rooms.rb
  test/factories/tracks.rb
Labels: Priority: High, Type: Feature, State: Ongoing Review

#121 Clear cache when user suddenly exists while playing the game
  app/javascript/packs/game.js
  app/views/rooms/show.html.haml
Labels: Type: ☹︎ Bug, Priority: High, State: Complete

#111 Submit and post answer feature
  app/controllers/rooms_controller.rb
  app/javascript/packs/api/index.js
  app/javascript/packs/api/request.js
  app/javascript/packs/api/room.js
  app/javascript/packs/api/url.js
  app/javascript/packs/game.js
  app/javascript/packs/model/question.js
  app/javascript/packs/playlist.js
  app/views/rooms/show.html.haml
  spec/requests/rooms_spec.rb
Labels: Priority: High, Type: Feature, State: Complete

#123 Prod mailer
  config/environments/development.rb
  config/environments/production.rb
Labels: Type: Feature

#124 Display answer feature
  app/javascript/packs/game.js
  app/javascript/packs/model/question.js
  app/javascript/packs/playlist.js
  app/views/rooms/show.html.haml
Labels: Priority: Medium, Type: Feature, State: Ongoing Review

#128 Fix Heroku Styles
  app/javascript/packs/application.js
  app/javascript/stylesheets/_base.scss
  app/javascript/stylesheets/_buttons.scss
  app/javascript/stylesheets/_inputs.scss
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/main.scss
  yarn.lock
Labels: Priority: Medium, Type: ❏ Visualization

#126 Display earned points feature
  app/javascript/packs/game.js
  app/views/layouts/_header.html.haml
  app/views/rooms/show.html.haml
Labels: Type: ★ Enhancement, Priority: Medium, State: Ongoing Review

#129 Display track number when playing the game
  app/javascript/packs/game.js
  app/javascript/stylesheets/_buttons.scss
  app/javascript/stylesheets/_variables.scss
  app/views/rooms/show.html.haml
Labels: Type: ★ Enhancement, Priority: Medium, State: Ongoing Review

#117 Bump Mailer Update
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/_typography.scss
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/email.css.scss
  app/mailer/devise_custom_mailer.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/layouts/mailer.html.erb
  config/initializers/devise.rb
  test/mailers/previews/devise_mailer_preview.rb
Labels: Type: ❏ Visualization

#135 All rooms and landing page style
  app/views/home_page/landing.html.haml
  app/views/rooms/index.html.haml
  public/user-with-note.svg
  spec/system/search_game_rooms_spec.rb
  spec/system/show_game_rooms_spec.rb
Labels: State: In Progress, Type: ❏ Visualization

#132 Update README file
  README.md
Labels: Type: ✎ Docs, Priority: High, State: Ongoing Review
